/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: order.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
// @ts-nocheck
import * as dependency_1 from "./enums";
import * as dependency_2 from "./payload";
import * as pb_1 from "google-protobuf";
// @ts-nocheck
export class PurchasePackageSimpleDetail extends pb_1.Message {
  #one_of_decls: number[][] = [];
  constructor(
    data?:
      | any[]
      | {
          purchasePackageId?: string;
          name?: string;
          discountedPrice?: number;
          originalPrice?: number;
          merchantId?: string;
          merchantName?: string;
          phoneNumber?: string[];
          merchantUid?: string;
          theme?: dependency_2.MediaMetaModel;
        }
  ) {
    super();
    pb_1.Message.initialize(
      this,
      Array.isArray(data) ? data : [],
      0,
      -1,
      [7],
      this.#one_of_decls
    );
    if (!Array.isArray(data) && typeof data == "object") {
      if ("purchasePackageId" in data && data.purchasePackageId != undefined) {
        this.purchasePackageId = data.purchasePackageId;
      }
      if ("name" in data && data.name != undefined) {
        this.name = data.name;
      }
      if ("discountedPrice" in data && data.discountedPrice != undefined) {
        this.discountedPrice = data.discountedPrice;
      }
      if ("originalPrice" in data && data.originalPrice != undefined) {
        this.originalPrice = data.originalPrice;
      }
      if ("merchantId" in data && data.merchantId != undefined) {
        this.merchantId = data.merchantId;
      }
      if ("merchantName" in data && data.merchantName != undefined) {
        this.merchantName = data.merchantName;
      }
      if ("phoneNumber" in data && data.phoneNumber != undefined) {
        this.phoneNumber = data.phoneNumber;
      }
      if ("merchantUid" in data && data.merchantUid != undefined) {
        this.merchantUid = data.merchantUid;
      }
      if ("theme" in data && data.theme != undefined) {
        this.theme = data.theme;
      }
    }
  }
  get purchasePackageId() {
    return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
  }
  set purchasePackageId(value: string) {
    pb_1.Message.setField(this, 1, value);
  }
  get name() {
    return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
  }
  set name(value: string) {
    pb_1.Message.setField(this, 2, value);
  }
  get discountedPrice() {
    return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
  }
  set discountedPrice(value: number) {
    pb_1.Message.setField(this, 3, value);
  }
  get originalPrice() {
    return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
  }
  set originalPrice(value: number) {
    pb_1.Message.setField(this, 4, value);
  }
  get merchantId() {
    return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
  }
  set merchantId(value: string) {
    pb_1.Message.setField(this, 5, value);
  }
  get merchantName() {
    return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
  }
  set merchantName(value: string) {
    pb_1.Message.setField(this, 6, value);
  }
  get phoneNumber() {
    return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
  }
  set phoneNumber(value: string[]) {
    pb_1.Message.setField(this, 7, value);
  }
  get merchantUid() {
    return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
  }
  set merchantUid(value: string) {
    pb_1.Message.setField(this, 8, value);
  }
  get theme() {
    return pb_1.Message.getWrapperField(
      this,
      dependency_2.MediaMetaModel,
      9
    ) as dependency_2.MediaMetaModel;
  }
  set theme(value: dependency_2.MediaMetaModel) {
    pb_1.Message.setWrapperField(this, 9, value);
  }
  get hasTheme() {
    return pb_1.Message.getField(this, 9) != null;
  }
  static fromObject(data: {
    purchasePackageId?: string;
    name?: string;
    discountedPrice?: number;
    originalPrice?: number;
    merchantId?: string;
    merchantName?: string;
    phoneNumber?: string[];
    merchantUid?: string;
    theme?: ReturnType<typeof dependency_2.MediaMetaModel.prototype.toObject>;
  }): PurchasePackageSimpleDetail {
    const message = new PurchasePackageSimpleDetail({});
    if (data.purchasePackageId != null) {
      message.purchasePackageId = data.purchasePackageId;
    }
    if (data.name != null) {
      message.name = data.name;
    }
    if (data.discountedPrice != null) {
      message.discountedPrice = data.discountedPrice;
    }
    if (data.originalPrice != null) {
      message.originalPrice = data.originalPrice;
    }
    if (data.merchantId != null) {
      message.merchantId = data.merchantId;
    }
    if (data.merchantName != null) {
      message.merchantName = data.merchantName;
    }
    if (data.phoneNumber != null) {
      message.phoneNumber = data.phoneNumber;
    }
    if (data.merchantUid != null) {
      message.merchantUid = data.merchantUid;
    }
    if (data.theme != null) {
      message.theme = dependency_2.MediaMetaModel.fromObject(data.theme);
    }
    return message;
  }
  toObject() {
    const data: {
      purchasePackageId?: string;
      name?: string;
      discountedPrice?: number;
      originalPrice?: number;
      merchantId?: string;
      merchantName?: string;
      phoneNumber?: string[];
      merchantUid?: string;
      theme?: ReturnType<typeof dependency_2.MediaMetaModel.prototype.toObject>;
    } = {};
    if (this.purchasePackageId != null) {
      data.purchasePackageId = this.purchasePackageId;
    }
    if (this.name != null) {
      data.name = this.name;
    }
    if (this.discountedPrice != null) {
      data.discountedPrice = this.discountedPrice;
    }
    if (this.originalPrice != null) {
      data.originalPrice = this.originalPrice;
    }
    if (this.merchantId != null) {
      data.merchantId = this.merchantId;
    }
    if (this.merchantName != null) {
      data.merchantName = this.merchantName;
    }
    if (this.phoneNumber != null) {
      data.phoneNumber = this.phoneNumber;
    }
    if (this.merchantUid != null) {
      data.merchantUid = this.merchantUid;
    }
    if (this.theme != null) {
      data.theme = this.theme.toObject();
    }
    return data;
  }
  serialize(): Uint8Array;
  serialize(w: pb_1.BinaryWriter): void;
  serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
    const writer = w || new pb_1.BinaryWriter();
    if (this.purchasePackageId.length)
      writer.writeString(1, this.purchasePackageId);
    if (this.name.length) writer.writeString(2, this.name);
    if (this.discountedPrice != 0) writer.writeUint64(3, this.discountedPrice);
    if (this.originalPrice != 0) writer.writeUint64(4, this.originalPrice);
    if (this.merchantId.length) writer.writeString(5, this.merchantId);
    if (this.merchantName.length) writer.writeString(6, this.merchantName);
    if (this.phoneNumber.length)
      writer.writeRepeatedString(7, this.phoneNumber);
    if (this.merchantUid.length) writer.writeString(8, this.merchantUid);
    if (this.hasTheme)
      writer.writeMessage(9, this.theme, () => this.theme.serialize(writer));
    if (!w) return writer.getResultBuffer();
  }
  static deserialize(
    bytes: Uint8Array | pb_1.BinaryReader
  ): PurchasePackageSimpleDetail {
    const reader =
        bytes instanceof pb_1.BinaryReader
          ? bytes
          : new pb_1.BinaryReader(bytes),
      message = new PurchasePackageSimpleDetail();
    while (reader.nextField()) {
      if (reader.isEndGroup()) break;
      switch (reader.getFieldNumber()) {
        case 1:
          message.purchasePackageId = reader.readString();
          break;
        case 2:
          message.name = reader.readString();
          break;
        case 3:
          message.discountedPrice = reader.readUint64();
          break;
        case 4:
          message.originalPrice = reader.readUint64();
          break;
        case 5:
          message.merchantId = reader.readString();
          break;
        case 6:
          message.merchantName = reader.readString();
          break;
        case 7:
          pb_1.Message.addToRepeatedField(message, 7, reader.readString());
          break;
        case 8:
          message.merchantUid = reader.readString();
          break;
        case 9:
          reader.readMessage(
            message.theme,
            () =>
              (message.theme = dependency_2.MediaMetaModel.deserialize(reader))
          );
          break;
        default:
          reader.skipField();
      }
    }
    return message;
  }
  serializeBinary(): Uint8Array {
    return this.serialize();
  }
  static deserializeBinary(bytes: Uint8Array): PurchasePackageSimpleDetail {
    return PurchasePackageSimpleDetail.deserialize(bytes);
  }
}
export class OrderPlaceRequest extends pb_1.Message {
  #one_of_decls: number[][] = [];
  constructor(
    data?:
      | any[]
      | {
          purchasePackageId?: string;
          addressId?: string;
          petId?: string;
          bookingRange?: dependency_2.TimeRange;
          remark?: string;
        }
  ) {
    super();
    pb_1.Message.initialize(
      this,
      Array.isArray(data) ? data : [],
      0,
      -1,
      [],
      this.#one_of_decls
    );
    if (!Array.isArray(data) && typeof data == "object") {
      if ("purchasePackageId" in data && data.purchasePackageId != undefined) {
        this.purchasePackageId = data.purchasePackageId;
      }
      if ("addressId" in data && data.addressId != undefined) {
        this.addressId = data.addressId;
      }
      if ("petId" in data && data.petId != undefined) {
        this.petId = data.petId;
      }
      if ("bookingRange" in data && data.bookingRange != undefined) {
        this.bookingRange = data.bookingRange;
      }
      if ("remark" in data && data.remark != undefined) {
        this.remark = data.remark;
      }
    }
  }
  get purchasePackageId() {
    return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
  }
  set purchasePackageId(value: string) {
    pb_1.Message.setField(this, 1, value);
  }
  get addressId() {
    return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
  }
  set addressId(value: string) {
    pb_1.Message.setField(this, 2, value);
  }
  get petId() {
    return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
  }
  set petId(value: string) {
    pb_1.Message.setField(this, 3, value);
  }
  get bookingRange() {
    return pb_1.Message.getWrapperField(
      this,
      dependency_2.TimeRange,
      4
    ) as dependency_2.TimeRange;
  }
  set bookingRange(value: dependency_2.TimeRange) {
    pb_1.Message.setWrapperField(this, 4, value);
  }
  get hasBookingRange() {
    return pb_1.Message.getField(this, 4) != null;
  }
  get remark() {
    return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
  }
  set remark(value: string) {
    pb_1.Message.setField(this, 5, value);
  }
  static fromObject(data: {
    purchasePackageId?: string;
    addressId?: string;
    petId?: string;
    bookingRange?: ReturnType<typeof dependency_2.TimeRange.prototype.toObject>;
    remark?: string;
  }): OrderPlaceRequest {
    const message = new OrderPlaceRequest({});
    if (data.purchasePackageId != null) {
      message.purchasePackageId = data.purchasePackageId;
    }
    if (data.addressId != null) {
      message.addressId = data.addressId;
    }
    if (data.petId != null) {
      message.petId = data.petId;
    }
    if (data.bookingRange != null) {
      message.bookingRange = dependency_2.TimeRange.fromObject(
        data.bookingRange
      );
    }
    if (data.remark != null) {
      message.remark = data.remark;
    }
    return message;
  }
  toObject() {
    const data: {
      purchasePackageId?: string;
      addressId?: string;
      petId?: string;
      bookingRange?: ReturnType<
        typeof dependency_2.TimeRange.prototype.toObject
      >;
      remark?: string;
    } = {};
    if (this.purchasePackageId != null) {
      data.purchasePackageId = this.purchasePackageId;
    }
    if (this.addressId != null) {
      data.addressId = this.addressId;
    }
    if (this.petId != null) {
      data.petId = this.petId;
    }
    if (this.bookingRange != null) {
      data.bookingRange = this.bookingRange.toObject();
    }
    if (this.remark != null) {
      data.remark = this.remark;
    }
    return data;
  }
  serialize(): Uint8Array;
  serialize(w: pb_1.BinaryWriter): void;
  serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
    const writer = w || new pb_1.BinaryWriter();
    if (this.purchasePackageId.length)
      writer.writeString(1, this.purchasePackageId);
    if (this.addressId.length) writer.writeString(2, this.addressId);
    if (this.petId.length) writer.writeString(3, this.petId);
    if (this.hasBookingRange)
      writer.writeMessage(4, this.bookingRange, () =>
        this.bookingRange.serialize(writer)
      );
    if (this.remark.length) writer.writeString(5, this.remark);
    if (!w) return writer.getResultBuffer();
  }
  static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OrderPlaceRequest {
    const reader =
        bytes instanceof pb_1.BinaryReader
          ? bytes
          : new pb_1.BinaryReader(bytes),
      message = new OrderPlaceRequest();
    while (reader.nextField()) {
      if (reader.isEndGroup()) break;
      switch (reader.getFieldNumber()) {
        case 1:
          message.purchasePackageId = reader.readString();
          break;
        case 2:
          message.addressId = reader.readString();
          break;
        case 3:
          message.petId = reader.readString();
          break;
        case 4:
          reader.readMessage(
            message.bookingRange,
            () =>
              (message.bookingRange =
                dependency_2.TimeRange.deserialize(reader))
          );
          break;
        case 5:
          message.remark = reader.readString();
          break;
        default:
          reader.skipField();
      }
    }
    return message;
  }
  serializeBinary(): Uint8Array {
    return this.serialize();
  }
  static deserializeBinary(bytes: Uint8Array): OrderPlaceRequest {
    return OrderPlaceRequest.deserialize(bytes);
  }
}
export class OrderPlaceResponse extends pb_1.Message {
  #one_of_decls: number[][] = [];
  constructor(data?: any[] | {}) {
    super();
    pb_1.Message.initialize(
      this,
      Array.isArray(data) ? data : [],
      0,
      -1,
      [],
      this.#one_of_decls
    );
    if (!Array.isArray(data) && typeof data == "object") {
    }
  }
  static fromObject(data: {}): OrderPlaceResponse {
    const message = new OrderPlaceResponse({});
    return message;
  }
  toObject() {
    const data: {} = {};
    return data;
  }
  serialize(): Uint8Array;
  serialize(w: pb_1.BinaryWriter): void;
  serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
    const writer = w || new pb_1.BinaryWriter();
    if (!w) return writer.getResultBuffer();
  }
  static deserialize(
    bytes: Uint8Array | pb_1.BinaryReader
  ): OrderPlaceResponse {
    const reader =
        bytes instanceof pb_1.BinaryReader
          ? bytes
          : new pb_1.BinaryReader(bytes),
      message = new OrderPlaceResponse();
    while (reader.nextField()) {
      if (reader.isEndGroup()) break;
      switch (reader.getFieldNumber()) {
        default:
          reader.skipField();
      }
    }
    return message;
  }
  serializeBinary(): Uint8Array {
    return this.serialize();
  }
  static deserializeBinary(bytes: Uint8Array): OrderPlaceResponse {
    return OrderPlaceResponse.deserialize(bytes);
  }
}
